/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvidenceEvidenceIdRouteImport } from './routes/evidence.$evidenceId'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceEvidenceIdRoute = EvidenceEvidenceIdRouteImport.update({
  id: '/evidence/$evidenceId',
  path: '/evidence/$evidenceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/submit': typeof SubmitRoute
  '/evidence/$evidenceId': typeof EvidenceEvidenceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/submit': typeof SubmitRoute
  '/evidence/$evidenceId': typeof EvidenceEvidenceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/submit': typeof SubmitRoute
  '/evidence/$evidenceId': typeof EvidenceEvidenceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/graph' | '/submit' | '/evidence/$evidenceId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/graph' | '/submit' | '/evidence/$evidenceId'
  id: '__root__' | '/' | '/graph' | '/submit' | '/evidence/$evidenceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraphRoute: typeof GraphRoute
  SubmitRoute: typeof SubmitRoute
  EvidenceEvidenceIdRoute: typeof EvidenceEvidenceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/$evidenceId': {
      id: '/evidence/$evidenceId'
      path: '/evidence/$evidenceId'
      fullPath: '/evidence/$evidenceId'
      preLoaderRoute: typeof EvidenceEvidenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraphRoute: GraphRoute,
  SubmitRoute: SubmitRoute,
  EvidenceEvidenceIdRoute: EvidenceEvidenceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
