apiVersion: v1
kind: Secret
metadata:
  name: worker-secret
type: Opaque
stringData:
  DATABASE_URL: postgresql://chainsight:123456789@host.k0s.internal:5433/chainsight?sslmode=disable
  IPFS_API_URL: http://ipfs:5001/api/v0/add
  PG_LISTEN_CHANNEL: chainsight_evidence_created
