apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: contract-service
  name: contract-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contract-service
  template:
    metadata:
      labels:
        app: contract-service
    spec:
      containers:
      - image: phakeandy/contract-service:dev
        name: "contract-service"

