apiVersion: v1
kind: Secret
metadata:
  name: contract-service-secret
type: Opaque
stringData:
  CHAIN_RPC_URL: http://hardhat:8545
  EVIDENCE_ANCHOR_ADDRESS: "0x0000000000000000000000000000000000000000"
