apiVersion: v1
kind: Service
metadata:
  labels:
    app: ipfs
  name: ipfs
spec:
  selector:
    app: ipfs
  ports:
    - name: p2p
      port: 4001
      protocol: TCP
      targetPort: p2p
    - name: api
      port: 5001
      protocol: TCP
      targetPort: api
    - name: gateway
      port: 8080
      protocol: TCP
      targetPort: gateway
